### ISSUE TITLE
What is the purpose of the repository?

### ISSUE THREAD

**Issue by artiswilliams** [midasdev711/MyCrawlers#1]
Hi.  I am a developer for one of the sites in your list of scrapers and your repository showed up in a security threat assessment tool because it references our site.  

Can you shed some light on what the purpose and intended use of the location data is?  While we didn't intend the data feed to be used in this way, we simply want to find out some information about how the data is being used since it is not self-evident by looking at the repo.

Thanks,
Art

**Comment by midasdev711** [comment]
Hi, Art.

I built these scrapers to get location data which will be used on a new website.
The new website will be more comfortable for users by showing locations on one page.
Users can easily find and reach restaurants, banks or companies in a specific area with the scraped data.
It is not used for a bad purpose.

Thanks,

Midas
